apiVersion: v1
kind: Service
metadata:
  name: quarkus-app
  labels:
    app: quarkus-app
spec:
  type: ClusterIP
  ports:
    # the port that this service should serve on
    - port: 9900
      targetPort: 9900
  selector:
    app: quarkus-app
